require 'hashie/mash'

require_relative 'elasticsearch_model_repositories/base_strategy'
require_relative 'elasticsearch_model_repositories/version'
require_relative 'elasticsearch_model_repositories/model'
require_relative 'elasticsearch_model_repositories/importing'
require_relative 'elasticsearch_model_repositories/response'
